propGroup = propGroup or {}

propGroup.everything = {
	"Decorative_Post",
	"Street_Light",
	"Street_Light_Midtown",
	"Street_Light_Modern",
	"Street_Light_Wooden",
	"twin_span_lamp",
	"chinese_lantern",
	"Campaign_Slogan__Board",
	"Ad_Stand_Tall_Round",
	"Bus_Stop",
	"Bus_Stop_Chinatown",
	"Bus_Stop_Coastal",
	"Bus_Stop_Financial",
	"Bus_Stop_Industrial",
	"Bus_Stop_residential_01",
	"Bus_Stop_residential_02",
	"Bus_Stop_Rural",
	"Hydrant",
	"Phone_Booth",
	"Phone_Booth_02",
	"Phone_Booth_ChinaTown",
	"Parking_Meter",
	"Parking_Meter_Double",
	"Parasol_01",
	"Parasol_02",
	"Parasol_03",
	"Plastic_Chair",
	"Plastic_Table",
	"divided_road_Sign",
	"Falling_rock_Sign",
	"max_speed_Sign",
	"No_Entry_Sign",
	"Snake_road_Sign",
	"Chainlink_Fence_Door_01",
	"Chainlink_Fence_Gate",
	"Chainlink_Fence_Tall_01",
	"Bench",
	"Dumpster_01",
	"Dumpster_02",
	"Post_Box_01",
	"Post_Box_02",
	"CardboardBox_Stack",
	"CardboardBox_01",
	"CardboardBox_02",
	"CardboardBox_03",
	"Bike_Black",
	"Bike_Blue",
	"Bike_Red",
	"Dumpster_01",
	"Dumpster_02",
	"Rubbish_Bin",
	"Rubbish_Bin_02",
	"Wheelie_Bin_01",
}



