routes = routes or {}
routes.SmalleyMcnalley = {}
routes.SmalleyMcnalley.arrows = {}
routes.SmalleyMcnalley.checkpoints = {}
routes.SmalleyMcnalley.checkpoints[1] = {}
routes.SmalleyMcnalley.checkpoints[1].position = vec.vector(118.3654, 21.26483, 4162.027, 1)
routes.SmalleyMcnalley.checkpoints[1].heading = 0.8236223
routes.SmalleyMcnalley.checkpoints[1].roadName = "sutro_shortcut_e_02 AI Road 2"
routes.SmalleyMcnalley.checkpoints[2] = {}
routes.SmalleyMcnalley.checkpoints[2].position = vec.vector(346.1235, 8.227503, 4190.896, 1)
routes.SmalleyMcnalley.checkpoints[2].heading = 1.59538
routes.SmalleyMcnalley.checkpoints[2].roadName = "sutro_shortcut_e_02 AI Road 2"
routes.SmalleyMcnalley.checkpoints[3] = {}
routes.SmalleyMcnalley.checkpoints[3].position = vec.vector(699.6743, 8.232735, 4188.757, 1)
routes.SmalleyMcnalley.checkpoints[3].heading = 1.715606
routes.SmalleyMcnalley.checkpoints[3].roadName = "sutro_shortcut_e_02 AI Road 2"
routes.SmalleyMcnalley.checkpoints[4] = {}
routes.SmalleyMcnalley.checkpoints[4].position = vec.vector(911.4769, 8.22987, 4048.27, 1)
routes.SmalleyMcnalley.checkpoints[4].heading = 2.293194
routes.SmalleyMcnalley.checkpoints[4].roadName = "sutro_shortcut_e_02 AI Road 1"
routes.SmalleyMcnalley.checkpoints[5] = {}
routes.SmalleyMcnalley.checkpoints[5].position = vec.vector(1020.153, 8.251161, 3949.11, 1)
routes.SmalleyMcnalley.checkpoints[5].heading = -0.8593448
routes.SmalleyMcnalley.checkpoints[5].roadName = "sutro_shortcut_e_02 AI Road 0"
routes.SmalleyMcnalley.roads = {}
routes.SmalleyMcnalley.roads[1] = {}
routes.SmalleyMcnalley.roads[1].road = "sutro_shortcut_e_02 AI Road 2"
routes.SmalleyMcnalley.roads[1].direction = "against"
routes.SmalleyMcnalley.roads[2] = {}
routes.SmalleyMcnalley.roads[2].road = "sutro_shortcut_e_02 AI Road 2"
routes.SmalleyMcnalley.roads[2].direction = "against"
routes.SmalleyMcnalley.roads[3] = {}
routes.SmalleyMcnalley.roads[3].road = "sutro_shortcut_e_02 AI Road 2"
routes.SmalleyMcnalley.roads[3].direction = "against"
routes.SmalleyMcnalley.roads[4] = {}
routes.SmalleyMcnalley.roads[4].road = "sutro_shortcut_e_02 AI Road 1"
routes.SmalleyMcnalley.roads[4].direction = "against"
routes.SmalleyMcnalley.roads[5] = {}
routes.SmalleyMcnalley.roads[5].road = "sutro_shortcut_e_02 AI Road 0"
routes.SmalleyMcnalley.roads[5].direction = "against"
routes["SmalleyMcnalley Start"] = {}
routes["SmalleyMcnalley Start"].checkpoints = {}
routes["SmalleyMcnalley Start"].checkpoints[1] = {}
routes["SmalleyMcnalley Start"].checkpoints[1].position = vec.vector(84.10374, 21.42151, 4135.518, 1)
routes["SmalleyMcnalley Start"].checkpoints[1].heading = 0.9108076
routes["SmalleyMcnalley Start"].checkpoints[1].roadName = "sutro_shortcut_e_02 AI Road 2"
routes["SmalleyMcnalley Start"].arrows = {}
routes["SmalleyMcnalley Start"].roads = {}
routes["SmalleyMcnalley Target"] = {}
routes["SmalleyMcnalley Target"].checkpoints = {}
routes["SmalleyMcnalley Target"].checkpoints[1] = {}
routes["SmalleyMcnalley Target"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["SmalleyMcnalley Target"].checkpoints[1].heading = -2.6058
routes["SmalleyMcnalley Target"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["SmalleyMcnalley Target"].checkpoints[2] = {}
routes["SmalleyMcnalley Target"].checkpoints[2].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["SmalleyMcnalley Target"].checkpoints[2].heading = -2.6058
routes["SmalleyMcnalley Target"].checkpoints[2].roadName = "dt_shortcut_29 AI Road 0"
routes["SmalleyMcnalley Target"].arrows = {}
routes["SmalleyMcnalley Target"].roads = {}
routes["SmalleyMcnalley Target"].roads[1] = {}
routes["SmalleyMcnalley Target"].roads[1].road = "dt_shortcut_29 AI Road 0"
routes["SmalleyMcnalley Target"].roads[1].direction = "against"
routes["SmalleyMcnalley Target"].roads[2] = {}
routes["SmalleyMcnalley Target"].roads[2].road = "dt_shortcut_29 AI Road 0"
routes["SmalleyMcnalley Target"].roads[2].direction = "with"
