routes["From Initial Garage To Downtown"] = {}
routes["From Initial Garage To Downtown"].arrows = {}
routes["From Initial Garage To Downtown"].checkpoints = {}
routes["From Initial Garage To Downtown"].roads = {}
routes["From Initial Garage To Downtown"].checkpoints[1] = {}
routes["From Initial Garage To Downtown"].checkpoints[1].position = vec.vector(174.95985412598, 16.632530212402, 1066.2738037109, 1)
routes["From Initial Garage To Downtown"].checkpoints[1].heading = 0.2719652056694
routes["From Initial Garage To Downtown"].checkpoints[1].roadName = "dt_shortcut_04 AI Road 1"
routes["From Initial Garage To Downtown"].roads[1] = {}
routes["From Initial Garage To Downtown"].roads[1].road = "dt_6l_north_01 AI Road 0"
routes["From Initial Garage To Downtown"].roads[1].direction = "with"
routes["From Initial Garage To Downtown"].roads[2] = {}
routes["From Initial Garage To Downtown"].roads[2].road = "dt_6l_north_01 AI Road 1"
routes["From Initial Garage To Downtown"].roads[2].direction = "with"
routes["From Initial Garage To Downtown"].roads[3] = {}
routes["From Initial Garage To Downtown"].roads[3].road = "dt_6l_north_01 AI Road 2"
routes["From Initial Garage To Downtown"].roads[3].direction = "with"
routes["From Initial Garage To Downtown"].roads[4] = {}
routes["From Initial Garage To Downtown"].roads[4].road = "dt_6l_north_01 AI Road 3"
routes["From Initial Garage To Downtown"].roads[4].direction = "with"
routes["From Initial Garage To Downtown"].roads[5] = {}
routes["From Initial Garage To Downtown"].roads[5].road = "dt_6l_centre_01 AI Road 0"
routes["From Initial Garage To Downtown"].roads[5].direction = "with"
routes["From Initial Garage To Downtown"].roads[6] = {}
routes["From Initial Garage To Downtown"].roads[6].road = "dt_6l_centre_01 AI Road 1"
routes["From Initial Garage To Downtown"].roads[6].direction = "with"
routes["From Initial Garage To Downtown"].roads[7] = {}
routes["From Initial Garage To Downtown"].roads[7].road = "dt_6l_centre_01 AI Road 2"
routes["From Initial Garage To Downtown"].roads[7].direction = "with"
routes["From Initial Garage To Downtown"].roads[8] = {}
routes["From Initial Garage To Downtown"].roads[8].road = "dt_6l_centre_03 AI Road 1"
routes["From Initial Garage To Downtown"].roads[8].direction = "with"
routes["From Initial Garage To Downtown"].roads[9] = {}
routes["From Initial Garage To Downtown"].roads[9].road = "dt_shortcut_04 AI Road 0"
routes["From Initial Garage To Downtown"].roads[9].direction = "with"
routes["From Initial Garage To Downtown"].roads[10] = {}
routes["From Initial Garage To Downtown"].roads[10].road = "dt_shortcut_04 AI Road 1"
routes["From Initial Garage To Downtown"].roads[10].direction = "with"
routes["From Initial Garage To Downtown Start"] = {}
routes["From Initial Garage To Downtown Start"].arrows = {}
routes["From Initial Garage To Downtown Start"].checkpoints = {}
routes["From Initial Garage To Downtown Start"].roads = {}
routes["From Initial Garage To Downtown Start"].checkpoints[1] = {}
routes["From Initial Garage To Downtown Start"].checkpoints[1].position = vec.vector(-807.22998046875, 5.0194673538208, -209.29515075684, 1)
routes["From Initial Garage To Downtown Start"].checkpoints[1].heading = 0.081953845918179
routes["From Initial Garage To Downtown Start"].checkpoints[1].roadName = "garage_helper_02 AI Road 0"
routes["From Initial Garage To Downtown Start"].roads[1] = {}
routes["From Initial Garage To Downtown Start"].roads[1].road = "garage_helper_02 AI Road 0"
routes["From Initial Garage To Downtown Start"].roads[1].direction = "with"