routes = routes or {}
routes["Head-On Bang-On"] = {}
routes["Head-On Bang-On"].arrows = {}
routes["Head-On Bang-On"].checkpoints = {}
routes["Head-On Bang-On"].roads = {}
routes["Head-On Bang-On"].checkpoints[1] = {}
routes["Head-On Bang-On"].checkpoints[1].position = vec.vector(-1005.952, 56.90419, 1274.133, 1)
routes["Head-On Bang-On"].checkpoints[1].heading = -2.98286
routes["Head-On Bang-On"].checkpoints[1].roadName = "highway01_16b AI Road 1"
routes["Head-On Bang-On"].roads[1] = {}
routes["Head-On Bang-On"].roads[1].road = "highway01_16b AI Road 1"
routes["Head-On Bang-On"].roads[1].direction = "against"
routes["Head-On Bang-On"].checkpoints[2] = {}
routes["Head-On Bang-On"].checkpoints[2].position = vec.vector(-1099.313, 56.9183, 1016.596, 1)
routes["Head-On Bang-On"].checkpoints[2].heading = -2.397281
routes["Head-On Bang-On"].checkpoints[2].roadName = "highway_split_sanfran_02 AI Road 0"
routes["Head-On Bang-On"].roads[2] = {}
routes["Head-On Bang-On"].roads[2].road = "highway_split_sanfran_02 AI Road 0"
routes["Head-On Bang-On"].roads[2].direction = "with"
routes["Head-On Bang-On"].checkpoints[3] = {}
routes["Head-On Bang-On"].checkpoints[3].position = vec.vector(-1402.01, 60.02551, 883.5759, 1)
routes["Head-On Bang-On"].checkpoints[3].heading = -1.812589
routes["Head-On Bang-On"].checkpoints[3].roadName = "highway_split_sanfran_02 AI Road 1"
routes["Head-On Bang-On"].roads[3] = {}
routes["Head-On Bang-On"].roads[3].road = "highway_split_sanfran_02 AI Road 1"
routes["Head-On Bang-On"].roads[3].direction = "with"
routes["Head-On Bang-On"].checkpoints[4] = {}
routes["Head-On Bang-On"].checkpoints[4].position = vec.vector(-1665.908, 60.04249, 776.153, 1)
routes["Head-On Bang-On"].checkpoints[4].heading = -2.068663
routes["Head-On Bang-On"].checkpoints[4].roadName = "highway_split_sanfran_02 AI Road 3"
routes["Head-On Bang-On"].roads[4] = {}
routes["Head-On Bang-On"].roads[4].road = "highway_split_sanfran_02 AI Road 3"
routes["Head-On Bang-On"].roads[4].direction = "with"
routes["Head-On Bang-On"].checkpoints[5] = {}
routes["Head-On Bang-On"].checkpoints[5].position = vec.vector(-1908.262, 24.42299, 515.9548, 1)
routes["Head-On Bang-On"].checkpoints[5].heading = -2.57154
routes["Head-On Bang-On"].checkpoints[5].roadName = "r387_helper_01 AI Road 0"
routes["Head-On Bang-On"].roads[5] = {}
routes["Head-On Bang-On"].roads[5].road = "r387_helper_01 AI Road 0"
routes["Head-On Bang-On"].roads[5].direction = "against"

routes["Head-On Bang-On"].arrows[1] = {}
routes["Head-On Bang-On"].arrows[1].position = vec.vector(-1860.926025, 57.014404, 608.538757, 1)
routes["Head-On Bang-On"].arrows[1].heading = 2.5444767
routes["Head-On Bang-On"].arrows[1].modelId = 78

routes["Head-On Bang-On Start"] = {}
routes["Head-On Bang-On Start"].checkpoints = {}
routes["Head-On Bang-On Start"].checkpoints[1] = {}
routes["Head-On Bang-On Start"].checkpoints[1].position = vec.vector(-932.6061, 73.25861, 1664.526, 1)
routes["Head-On Bang-On Start"].checkpoints[1].heading = -3.123742
routes["Head-On Bang-On Start"].checkpoints[1].roadName = "mt_sliprod_01 AI Road 0"
routes["Head-On Bang-On Start"].arrows = {}
routes["Head-On Bang-On Start"].roads = {}
routes["Head-On Bang-On Target"] = {}
routes["Head-On Bang-On Target"].checkpoints = {}
routes["Head-On Bang-On Target"].checkpoints[1] = {}
routes["Head-On Bang-On Target"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Head-On Bang-On Target"].checkpoints[1].heading = -2.6058
routes["Head-On Bang-On Target"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["Head-On Bang-On Target"].checkpoints[2] = {}
routes["Head-On Bang-On Target"].checkpoints[2].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Head-On Bang-On Target"].checkpoints[2].heading = -2.6058
routes["Head-On Bang-On Target"].checkpoints[2].roadName = "dt_shortcut_29 AI Road 0"
routes["Head-On Bang-On Target"].arrows = {}
routes["Head-On Bang-On Target"].roads = {}
routes["Head-On Bang-On Target"].roads[1] = {}
routes["Head-On Bang-On Target"].roads[1].road = "dt_shortcut_29 AI Road 0"
routes["Head-On Bang-On Target"].roads[1].direction = "against"
routes["Head-On Bang-On Target"].roads[2] = {}
routes["Head-On Bang-On Target"].roads[2].road = "dt_shortcut_29 AI Road 0"
routes["Head-On Bang-On Target"].roads[2].direction = "with"
