routes = routes or {}
routes["Qualifying Driver Madness 01"] = {}
routes["Qualifying Driver Madness 01"].checkpoints = {}
routes["Qualifying Driver Madness 01"].checkpoints[1] = {}
routes["Qualifying Driver Madness 01"].checkpoints[1].position = vec.vector(-3178.842285, 113.670403, -3164.785645, 1)
routes["Qualifying Driver Madness 01"].checkpoints[1].heading = 0.5876114
routes["Qualifying Driver Madness 01"].checkpoints[1].roadName = "marin_shortcut_07 AI Road 0"
routes["Qualifying Driver Madness 01"].checkpoints[2] = {}
routes["Qualifying Driver Madness 01"].checkpoints[2].position = vec.vector(-3078.571533, 113.672112, -3048.364014, 1)
routes["Qualifying Driver Madness 01"].checkpoints[2].heading = -2.4033585
routes["Qualifying Driver Madness 01"].checkpoints[2].roadName = "marin_shortcut_07 AI Road 0"
routes["Qualifying Driver Madness 01"].arrows = {}
routes["Qualifying Driver Madness 01"].roads = {}
routes["Qualifying Driver Madness 01"].roads[1] = {}
routes["Qualifying Driver Madness 01"].roads[1].road = "marin_shortcut_07 AI Road 0"
routes["Qualifying Driver Madness 01"].roads[1].direction = "with"
routes["Qualifying Driver Madness 01"].roads[2] = {}
routes["Qualifying Driver Madness 01"].roads[2].road = "highway01_15 AI Road 9"
routes["Qualifying Driver Madness 01"].roads[2].direction = "against"
routes["Qualifying Driver Madness 01"].roads[3] = {}
routes["Qualifying Driver Madness 01"].roads[3].road = "highway01_15 AI Road 8"
routes["Qualifying Driver Madness 01"].roads[3].direction = "against"
routes["Qualifying Driver Madness 01"].roads[4] = {}
routes["Qualifying Driver Madness 01"].roads[4].road = "highway01_15 AI Road 7"
routes["Qualifying Driver Madness 01"].roads[4].direction = "against"
