routes["Garage to Garage"] = {}
routes["Garage to Garage"].checkpoints = {}
routes["Garage to Garage"].checkpoints[1] = {}
routes["Garage to Garage"].checkpoints[1].position = vec.vector(122.25003051758, 18.285406112671, 1001.5411987305, 1)
routes["Garage to Garage"].checkpoints[1].heading = -1.4487606287003
routes["Garage to Garage"].checkpoints[1].roadName = "dt_10l_south_01 AI Road 3"
routes["Garage to Garage"].roads = {}
routes["Garage to Garage"].roads[1] = {}
routes["Garage to Garage"].roads[1].road = "marin_4l_centre_01 AI Road 14"
routes["Garage to Garage"].roads[1].direction = "against"
routes["Garage to Garage"].roads[2] = {}
routes["Garage to Garage"].roads[2].road = "marin_4l_centre_01 AI Road 13"
routes["Garage to Garage"].roads[2].direction = "against"
routes["Garage to Garage"].roads[3] = {}
routes["Garage to Garage"].roads[3].road = "r654_shortcut_01 AI Road 0"
routes["Garage to Garage"].roads[3].direction = "against"
routes["Garage to Garage"].roads[4] = {}
routes["Garage to Garage"].roads[4].road = "mountain_10l_w_01a AI Road 1"
routes["Garage to Garage"].roads[4].direction = "with"
routes["Garage to Garage"].roads[5] = {}
routes["Garage to Garage"].roads[5].road = "mountain_10l_w_01a AI Road 3"
routes["Garage to Garage"].roads[5].direction = "with"
routes["Garage to Garage"].roads[6] = {}
routes["Garage to Garage"].roads[6].road = "mountain_10l_w_01a AI Road 4"
routes["Garage to Garage"].roads[6].direction = "with"
routes["Garage to Garage"].roads[7] = {}
routes["Garage to Garage"].roads[7].road = "mountain_10l_w_01a AI Road 5"
routes["Garage to Garage"].roads[7].direction = "with"
routes["Garage to Garage"].roads[8] = {}
routes["Garage to Garage"].roads[8].road = "mountain_10l_w_01a AI Road 6"
routes["Garage to Garage"].roads[8].direction = "with"
routes["Garage to Garage"].roads[9] = {}
routes["Garage to Garage"].roads[9].road = "mountain_10l_w_01a AI Road 7"
routes["Garage to Garage"].roads[9].direction = "with"
routes["Garage to Garage"].roads[10] = {}
routes["Garage to Garage"].roads[10].road = "marin_sliproad_07 AI Road 0"
routes["Garage to Garage"].roads[10].direction = "with"
routes["Garage to Garage"].roads[11] = {}
routes["Garage to Garage"].roads[11].road = "mountain_10l_w_01b AI Road 0"
routes["Garage to Garage"].roads[11].direction = "against"
routes["Garage to Garage"].roads[12] = {}
routes["Garage to Garage"].roads[12].road = "marin_complex_03 AI Road 0"
routes["Garage to Garage"].roads[12].direction = "against"
routes["Garage to Garage"].roads[13] = {}
routes["Garage to Garage"].roads[13].road = "highway02_03 AI Road 22"
routes["Garage to Garage"].roads[13].direction = "against"
routes["Garage to Garage"].roads[14] = {}
routes["Garage to Garage"].roads[14].road = "highway02_03 AI Road 21"
routes["Garage to Garage"].roads[14].direction = "against"
routes["Garage to Garage"].roads[15] = {}
routes["Garage to Garage"].roads[15].road = "marin_sanraf_sliproad_01 AI Road 0"
routes["Garage to Garage"].roads[15].direction = "against"
routes["Garage to Garage"].roads[16] = {}
routes["Garage to Garage"].roads[16].road = "highway01_15 AI Road 50"
routes["Garage to Garage"].roads[16].direction = "with"
routes["Garage to Garage"].roads[17] = {}
routes["Garage to Garage"].roads[17].road = "highway01_15 AI Road 51"
routes["Garage to Garage"].roads[17].direction = "with"
routes["Garage to Garage"].roads[18] = {}
routes["Garage to Garage"].roads[18].road = "highway01_15 AI Road 52"
routes["Garage to Garage"].roads[18].direction = "with"
routes["Garage to Garage"].roads[19] = {}
routes["Garage to Garage"].roads[19].road = "highway01_15 AI Road 53"
routes["Garage to Garage"].roads[19].direction = "with"
routes["Garage to Garage"].roads[20] = {}
routes["Garage to Garage"].roads[20].road = "highway01_15 AI Road 54"
routes["Garage to Garage"].roads[20].direction = "with"
routes["Garage to Garage"].roads[21] = {}
routes["Garage to Garage"].roads[21].road = "highway01_15 AI Road 55"
routes["Garage to Garage"].roads[21].direction = "with"
routes["Garage to Garage"].roads[22] = {}
routes["Garage to Garage"].roads[22].road = "highway01_15 AI Road 56"
routes["Garage to Garage"].roads[22].direction = "with"
routes["Garage to Garage"].roads[23] = {}
routes["Garage to Garage"].roads[23].road = "highway01_15 AI Road 57"
routes["Garage to Garage"].roads[23].direction = "with"
routes["Garage to Garage"].roads[24] = {}
routes["Garage to Garage"].roads[24].road = "highway01_15 AI Road 58"
routes["Garage to Garage"].roads[24].direction = "with"
routes["Garage to Garage"].roads[25] = {}
routes["Garage to Garage"].roads[25].road = "highway01_15 AI Road 59"
routes["Garage to Garage"].roads[25].direction = "with"
routes["Garage to Garage"].roads[26] = {}
routes["Garage to Garage"].roads[26].road = "highway01_15 AI Road 60"
routes["Garage to Garage"].roads[26].direction = "with"
routes["Garage to Garage"].roads[27] = {}
routes["Garage to Garage"].roads[27].road = "highway01_15 AI Road 61"
routes["Garage to Garage"].roads[27].direction = "with"
routes["Garage to Garage"].roads[28] = {}
routes["Garage to Garage"].roads[28].road = "highway01_15 AI Road 62"
routes["Garage to Garage"].roads[28].direction = "with"
routes["Garage to Garage"].roads[29] = {}
routes["Garage to Garage"].roads[29].road = "superhighway_split_03 AI Road 5"
routes["Garage to Garage"].roads[29].direction = "against"
routes["Garage to Garage"].roads[30] = {}
routes["Garage to Garage"].roads[30].road = "superhighway_split_03 AI Road 4"
routes["Garage to Garage"].roads[30].direction = "against"
routes["Garage to Garage"].roads[31] = {}
routes["Garage to Garage"].roads[31].road = "superhighway_split_03 AI Road 3"
routes["Garage to Garage"].roads[31].direction = "against"
routes["Garage to Garage"].roads[32] = {}
routes["Garage to Garage"].roads[32].road = "superhighway_split_03 AI Road 2"
routes["Garage to Garage"].roads[32].direction = "against"
routes["Garage to Garage"].roads[33] = {}
routes["Garage to Garage"].roads[33].road = "superhighway_split_03 AI Road 1"
routes["Garage to Garage"].roads[33].direction = "against"
routes["Garage to Garage"].roads[34] = {}
routes["Garage to Garage"].roads[34].road = "superhighway_split_03 AI Road 0"
routes["Garage to Garage"].roads[34].direction = "against"
routes["Garage to Garage"].roads[35] = {}
routes["Garage to Garage"].roads[35].road = "superhighway_road_01 AI Road 0"
routes["Garage to Garage"].roads[35].direction = "with"
routes["Garage to Garage"].roads[36] = {}
routes["Garage to Garage"].roads[36].road = "superhighway_road_01 AI Road 1"
routes["Garage to Garage"].roads[36].direction = "with"
routes["Garage to Garage"].roads[37] = {}
routes["Garage to Garage"].roads[37].road = "superhighway_road_01 AI Road 2"
routes["Garage to Garage"].roads[37].direction = "with"
routes["Garage to Garage"].roads[38] = {}
routes["Garage to Garage"].roads[38].road = "superhighway_road_01 AI Road 3"
routes["Garage to Garage"].roads[38].direction = "with"
routes["Garage to Garage"].roads[39] = {}
routes["Garage to Garage"].roads[39].road = "superhighway_road_01 AI Road 4"
routes["Garage to Garage"].roads[39].direction = "with"
routes["Garage to Garage"].roads[40] = {}
routes["Garage to Garage"].roads[40].road = "superhighway_road_01 AI Road 5"
routes["Garage to Garage"].roads[40].direction = "with"
routes["Garage to Garage"].roads[41] = {}
routes["Garage to Garage"].roads[41].road = "superhighway_road_01 AI Road 6"
routes["Garage to Garage"].roads[41].direction = "with"
routes["Garage to Garage"].roads[42] = {}
routes["Garage to Garage"].roads[42].road = "superhighway_split_01 AI Road 3"
routes["Garage to Garage"].roads[42].direction = "against"
routes["Garage to Garage"].roads[43] = {}
routes["Garage to Garage"].roads[43].road = "superhighway_split_01 AI Road 2"
routes["Garage to Garage"].roads[43].direction = "against"
routes["Garage to Garage"].roads[44] = {}
routes["Garage to Garage"].roads[44].road = "superhighway_split_01 AI Road 1"
routes["Garage to Garage"].roads[44].direction = "against"
routes["Garage to Garage"].roads[45] = {}
routes["Garage to Garage"].roads[45].road = "superhighway_split_01 AI Road 0"
routes["Garage to Garage"].roads[45].direction = "against"
routes["Garage to Garage"].roads[46] = {}
routes["Garage to Garage"].roads[46].road = "superhighway_split_01 AI Road 0"
routes["Garage to Garage"].roads[46].direction = "against"
routes["Garage to Garage"].roads[47] = {}
routes["Garage to Garage"].roads[47].road = "highway01_16b AI Road 29"
routes["Garage to Garage"].roads[47].direction = "against"
routes["Garage to Garage"].roads[48] = {}
routes["Garage to Garage"].roads[48].road = "highway01_16b AI Road 28"
routes["Garage to Garage"].roads[48].direction = "against"
routes["Garage to Garage"].roads[49] = {}
routes["Garage to Garage"].roads[49].road = "highway01_16b AI Road 27"
routes["Garage to Garage"].roads[49].direction = "against"
routes["Garage to Garage"].roads[50] = {}
routes["Garage to Garage"].roads[50].road = "highway01_16b AI Road 26"
routes["Garage to Garage"].roads[50].direction = "against"
routes["Garage to Garage"].roads[51] = {}
routes["Garage to Garage"].roads[51].road = "highway01_16b AI Road 25"
routes["Garage to Garage"].roads[51].direction = "against"
routes["Garage to Garage"].roads[52] = {}
routes["Garage to Garage"].roads[52].road = "highway01_16b AI Road 24"
routes["Garage to Garage"].roads[52].direction = "against"
routes["Garage to Garage"].roads[53] = {}
routes["Garage to Garage"].roads[53].road = "highway01_16b AI Road 23"
routes["Garage to Garage"].roads[53].direction = "against"
routes["Garage to Garage"].roads[54] = {}
routes["Garage to Garage"].roads[54].road = "highway01_16b AI Road 22"
routes["Garage to Garage"].roads[54].direction = "against"
routes["Garage to Garage"].roads[55] = {}
routes["Garage to Garage"].roads[55].road = "highway01_16b AI Road 21"
routes["Garage to Garage"].roads[55].direction = "against"
routes["Garage to Garage"].roads[56] = {}
routes["Garage to Garage"].roads[56].road = "highway01_16b AI Road 20"
routes["Garage to Garage"].roads[56].direction = "against"
routes["Garage to Garage"].roads[57] = {}
routes["Garage to Garage"].roads[57].road = "bb_sliproad_02 AI Road 0"
routes["Garage to Garage"].roads[57].direction = "against"
routes["Garage to Garage"].roads[58] = {}
routes["Garage to Garage"].roads[58].road = "mt_10l_centre_03b AI Road 1"
routes["Garage to Garage"].roads[58].direction = "against"
routes["Garage to Garage"].roads[59] = {}
routes["Garage to Garage"].roads[59].road = "mt_10l_centre_03b AI Road 0"
routes["Garage to Garage"].roads[59].direction = "against"
routes["Garage to Garage"].roads[60] = {}
routes["Garage to Garage"].roads[60].road = "barcelero_alleyway_01 AI Road 1"
routes["Garage to Garage"].roads[60].direction = "against"
routes["Garage to Garage"].roads[61] = {}
routes["Garage to Garage"].roads[61].road = "barcelero_alleyway_01 AI Road 0"
routes["Garage to Garage"].roads[61].direction = "against"
routes["Garage to Garage"].roads[62] = {}
routes["Garage to Garage"].roads[62].road = "dt_10l_south_03 AI Road 3"
routes["Garage to Garage"].roads[62].direction = "against"
routes["Garage to Garage"].roads[63] = {}
routes["Garage to Garage"].roads[63].road = "dt_shortcut_15 AI Road 1"
routes["Garage to Garage"].roads[63].direction = "against"
routes["Garage to Garage"].roads[64] = {}
routes["Garage to Garage"].roads[64].road = "dt_shortcut_15 AI Road 0"
routes["Garage to Garage"].roads[64].direction = "against"
routes["Garage to Garage"].roads[65] = {}
routes["Garage to Garage"].roads[65].road = "dt_10l_south_01 AI Road 2"
routes["Garage to Garage"].roads[65].direction = "with"
routes["Garage to Garage"].roads[66] = {}
routes["Garage to Garage"].roads[66].road = "dt_10l_south_01 AI Road 3"
routes["Garage to Garage"].roads[66].direction = "with"
routes["Garage to Garage"].arrows = {}

routes["Garage to Garage Start"] = {}
routes["Garage to Garage Start"].arrows = {}
routes["Garage to Garage Start"].checkpoints = {}
routes["Garage to Garage Start"].roads = {}
routes["Garage to Garage Start"].checkpoints[1] = {}
routes["Garage to Garage Start"].checkpoints[1].position = vec.vector(1113.1612548828, 30.002645492554, -4179.791015625, 1)
routes["Garage to Garage Start"].checkpoints[1].heading = 1.3807504177094
routes["Garage to Garage Start"].checkpoints[1].roadName = "r654_helper_01 AI Road 0"
routes["Garage to Garage Start"].roads[1] = {}
routes["Garage to Garage Start"].roads[1].road = "r654_helper_01 AI Road 0"
routes["Garage to Garage Start"].roads[1].direction = "with"
