routes = routes or {}
routes["Around The World"] = {}
routes["Around The World"].arrows = {}
routes["Around The World"].checkpoints = {}
routes["Around The World"].roads = {}
routes["Around The World"].checkpoints[1] = {}
routes["Around The World"].checkpoints[1].position = vec.vector(-2536.019, 66.90424, 1001.905, 1)
routes["Around The World"].checkpoints[1].heading = -0.1121401
routes["Around The World"].checkpoints[1].roadName = "ggb_shortcut_07 AI Road 0"
routes["Around The World"].roads[1] = {}
routes["Around The World"].roads[1].road = "ggb_shortcut_07 AI Road 0"
routes["Around The World"].roads[1].direction = "with"
routes["Around The World"].checkpoints[2] = {}
routes["Around The World"].checkpoints[2].position = vec.vector(-2574.314, 67.76076, 1060.461, 1)
routes["Around The World"].checkpoints[2].heading = -1.210485
routes["Around The World"].checkpoints[2].roadName = "ggb_shortcut_07 AI Road 0"
routes["Around The World"].roads[2] = {}
routes["Around The World"].roads[2].road = "ggb_shortcut_07 AI Road 0"
routes["Around The World"].roads[2].direction = "with"
routes["Around The World"].checkpoints[3] = {}
routes["Around The World"].checkpoints[3].position = vec.vector(-2631.091, 69.0585, 1049.656, 1)
routes["Around The World"].checkpoints[3].heading = -2.368649
routes["Around The World"].checkpoints[3].roadName = "ggb_shortcut_07 AI Road 0"
routes["Around The World"].roads[3] = {}
routes["Around The World"].roads[3].road = "ggb_shortcut_07 AI Road 0"
routes["Around The World"].roads[3].direction = "with"
routes["Around The World"].checkpoints[4] = {}
routes["Around The World"].checkpoints[4].position = vec.vector(-2656.52, 69.07742, 992.9682, 1)
routes["Around The World"].checkpoints[4].heading = -3.104025
routes["Around The World"].checkpoints[4].roadName = "ggb_shortcut_06 AI Road 0"
routes["Around The World"].roads[4] = {}
routes["Around The World"].roads[4].road = "ggb_shortcut_06 AI Road 0"
routes["Around The World"].roads[4].direction = "with"
routes["Around The World"].checkpoints[5] = {}
routes["Around The World"].checkpoints[5].position = vec.vector(-2620.418, 68.16553, 928.997, 1)
routes["Around The World"].checkpoints[5].heading = 1.924486
routes["Around The World"].checkpoints[5].roadName = "ggb_shortcut_06 AI Road 0"
routes["Around The World"].roads[5] = {}
routes["Around The World"].roads[5].road = "ggb_shortcut_06 AI Road 0"
routes["Around The World"].roads[5].direction = "with"
routes["Around The World"].checkpoints[6] = {}
routes["Around The World"].checkpoints[6].position = vec.vector(-2557.651, 66.89367, 944.0651, 1)
routes["Around The World"].checkpoints[6].heading = 0.7093271
routes["Around The World"].checkpoints[6].roadName = "ggb_shortcut_06 AI Road 0"
routes["Around The World"].roads[6] = {}
routes["Around The World"].roads[6].road = "ggb_shortcut_06 AI Road 0"
routes["Around The World"].roads[6].direction = "with"
routes["Around The World Start"] = {}
routes["Around The World Start"].checkpoints = {}
routes["Around The World Start"].checkpoints[1] = {}
routes["Around The World Start"].checkpoints[1].position = vec.vector(-2573.757, 67.22585, 931.8374, 1)
routes["Around The World Start"].checkpoints[1].heading = 1.124857
routes["Around The World Start"].checkpoints[1].roadName = "ggb_shortcut_06 AI Road 0"
routes["Around The World Start"].arrows = {}
routes["Around The World Start"].roads = {}
routes["Around The World Target"] = {}
routes["Around The World Target"].checkpoints = {}
routes["Around The World Target"].checkpoints[1] = {}
routes["Around The World Target"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Around The World Target"].checkpoints[1].heading = -2.6058
routes["Around The World Target"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["Around The World Target"].checkpoints[2] = {}
routes["Around The World Target"].checkpoints[2].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Around The World Target"].checkpoints[2].heading = -2.6058
routes["Around The World Target"].checkpoints[2].roadName = "dt_shortcut_29 AI Road 0"
routes["Around The World Target"].arrows = {}
routes["Around The World Target"].roads = {}
routes["Around The World Target"].roads[1] = {}
routes["Around The World Target"].roads[1].road = "dt_shortcut_29 AI Road 0"
routes["Around The World Target"].roads[1].direction = "against"
routes["Around The World Target"].roads[2] = {}
routes["Around The World Target"].roads[2].road = "dt_shortcut_29 AI Road 0"
routes["Around The World Target"].roads[2].direction = "with"
