routes = routes or {}
routes.Bamboozled = {}
routes.Bamboozled.arrows = {}
routes.Bamboozled.checkpoints = {}
routes.Bamboozled.checkpoints[1] = {}
routes.Bamboozled.checkpoints[1].position = vec.vector(-4377.613, 26.59003, 3658.163, 1)
routes.Bamboozled.checkpoints[1].heading = -2.182977
routes.Bamboozled.checkpoints[1].roadName = "sutro_south_main AI Road 1"
routes.Bamboozled.checkpoints[2] = {}
routes.Bamboozled.checkpoints[2].position = vec.vector(-4440.604, 21.43325, 3300.712, 1)
routes.Bamboozled.checkpoints[2].heading = -3.139319
routes.Bamboozled.checkpoints[2].roadName = "sutro_south_main AI Road 0"
routes.Bamboozled.checkpoints[3] = {}
routes.Bamboozled.checkpoints[3].position = vec.vector(-4439.711, 21.40923, 2619.821, 1)
routes.Bamboozled.checkpoints[3].heading = -3.119429
routes.Bamboozled.checkpoints[3].roadName = "ggp_10l_west_01 AI Road 1"
routes.Bamboozled.checkpoints[4] = {}
routes.Bamboozled.checkpoints[4].position = vec.vector(-4435.147, 14.95968, 2104.072, 1)
routes.Bamboozled.checkpoints[4].heading = -3.131191
routes.Bamboozled.checkpoints[4].roadName = "ggp_10l_west_01 AI Road 4"
routes.Bamboozled.checkpoints[5] = {}
routes.Bamboozled.checkpoints[5].position = vec.vector(-4444.796, 21.74594, 1554.749, 1)
routes.Bamboozled.checkpoints[5].heading = -3.029041
routes.Bamboozled.checkpoints[5].roadName = "ggp_10l_west_01 AI Road 6"
routes.Bamboozled.checkpoints[6] = {}
routes.Bamboozled.checkpoints[6].position = vec.vector(-4449.546, 21.9722, 1533.276, 1)
routes.Bamboozled.checkpoints[6].heading = -3.028196
routes.Bamboozled.checkpoints[6].roadName = "ggp_10l_west_01 AI Road 6"
routes.Bamboozled.checkpoints[7] = {}
routes.Bamboozled.checkpoints[7].position = vec.vector(-4445.449, 21.0971, 2313.792, 1)
routes.Bamboozled.checkpoints[7].heading = 3.141593
routes.Bamboozled.checkpoints[7].roadName = "ggp_10l_west_01 AI Road 2"
routes.Bamboozled.checkpoints[8] = {}
routes.Bamboozled.checkpoints[8].position = vec.vector(-3735.477, 69.52079, 3984.375, 1)
routes.Bamboozled.checkpoints[8].heading = 1.468017
routes.Bamboozled.checkpoints[8].roadName = "sutro_south_main AI Road 6"
routes.Bamboozled.roads = {}
routes.Bamboozled.roads[1] = {}
routes.Bamboozled.roads[1].road = "sutro_south_main AI Road 1"
routes.Bamboozled.roads[1].direction = "against"
routes.Bamboozled.roads[2] = {}
routes.Bamboozled.roads[2].road = "sutro_south_main AI Road 0"
routes.Bamboozled.roads[2].direction = "against"
routes.Bamboozled.roads[3] = {}
routes.Bamboozled.roads[3].road = "ggp_10l_west_01 AI Road 1"
routes.Bamboozled.roads[3].direction = "with"
routes.Bamboozled.roads[4] = {}
routes.Bamboozled.roads[4].road = "ggp_10l_west_01 AI Road 4"
routes.Bamboozled.roads[4].direction = "with"
routes.Bamboozled.roads[5] = {}
routes.Bamboozled.roads[5].road = "ggp_10l_west_01 AI Road 6"
routes.Bamboozled.roads[5].direction = "with"
routes.Bamboozled.roads[6] = {}
routes.Bamboozled.roads[6].road = "ggp_10l_west_01 AI Road 6"
routes.Bamboozled.roads[6].direction = "with"
routes.Bamboozled.roads[7] = {}
routes.Bamboozled.roads[7].road = "ggp_10l_west_01 AI Road 2"
routes.Bamboozled.roads[7].direction = "against"
routes.Bamboozled.roads[8] = {}
routes.Bamboozled.roads[8].road = "sutro_south_main AI Road 6"
routes.Bamboozled.roads[8].direction = "with"
routes["Bamboozled Start"] = {}
routes["Bamboozled Start"].checkpoints = {}
routes["Bamboozled Start"].checkpoints[1] = {}
routes["Bamboozled Start"].checkpoints[1].position = vec.vector(-4185.789, 38.63422, 3758.492, 1)
routes["Bamboozled Start"].checkpoints[1].heading = 1.840874
routes["Bamboozled Start"].checkpoints[1].roadName = "sutro_south_main AI Road 2"
routes["Bamboozled Start"].arrows = {}
routes["Bamboozled Start"].roads = {}
routes["Bamboozled Target"] = {}
routes["Bamboozled Target"].checkpoints = {}
routes["Bamboozled Target"].checkpoints[1] = {}
routes["Bamboozled Target"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Bamboozled Target"].checkpoints[1].heading = -2.6058
routes["Bamboozled Target"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["Bamboozled Target"].checkpoints[2] = {}
routes["Bamboozled Target"].checkpoints[2].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Bamboozled Target"].checkpoints[2].heading = -2.6058
routes["Bamboozled Target"].checkpoints[2].roadName = "dt_shortcut_29 AI Road 0"
routes["Bamboozled Target"].arrows = {}
routes["Bamboozled Target"].roads = {}
routes["Bamboozled Target"].roads[1] = {}
routes["Bamboozled Target"].roads[1].road = "dt_shortcut_29 AI Road 0"
routes["Bamboozled Target"].roads[1].direction = "against"
routes["Bamboozled Target"].roads[2] = {}
routes["Bamboozled Target"].roads[2].road = "dt_shortcut_29 AI Road 0"
routes["Bamboozled Target"].roads[2].direction = "with"
