routes["Going Across"] = {}
routes["Going Across"].checkpoints = {}
routes["Going Across"].checkpoints[1] = {}
routes["Going Across"].checkpoints[1].position = vec.vector(-4282.3798828125, 43.232940673828, 3825.8400878906, 1)
routes["Going Across"].checkpoints[1].heading = 3.0532047748566
routes["Going Across"].checkpoints[1].roadName = "sutro_south_main AI Road 3"
routes["Going Across"].roads = {}
routes["Going Across"].roads[1] = {}
routes["Going Across"].roads[1].road = "dt_shortcut_07 AI Road 2"
routes["Going Across"].roads[1].direction = "against"
routes["Going Across"].roads[2] = {}
routes["Going Across"].roads[2].road = "dt_shortcut_07 AI Road 1"
routes["Going Across"].roads[2].direction = "against"
routes["Going Across"].roads[3] = {}
routes["Going Across"].roads[3].road = "dt_shortcut_07 AI Road 0"
routes["Going Across"].roads[3].direction = "against"
routes["Going Across"].roads[4] = {}
routes["Going Across"].roads[4].road = "dt_4l_north_01 AI Road 8"
routes["Going Across"].roads[4].direction = "with"
routes["Going Across"].roads[5] = {}
routes["Going Across"].roads[5].road = "dt_8l_centre_02 AI Road 0"
routes["Going Across"].roads[5].direction = "with"
routes["Going Across"].roads[6] = {}
routes["Going Across"].roads[6].road = "dt_8l_centre_02 AI Road 1"
routes["Going Across"].roads[6].direction = "with"
routes["Going Across"].roads[7] = {}
routes["Going Across"].roads[7].road = "dt_8l_centre_02 AI Road 2"
routes["Going Across"].roads[7].direction = "with"
routes["Going Across"].roads[8] = {}
routes["Going Across"].roads[8].road = "dt_8l_centre_02 AI Road 3"
routes["Going Across"].roads[8].direction = "with"
routes["Going Across"].roads[9] = {}
routes["Going Across"].roads[9].road = "dt_8l_centre_02 AI Road 4"
routes["Going Across"].roads[9].direction = "with"
routes["Going Across"].roads[10] = {}
routes["Going Across"].roads[10].road = "dt_8l_centre_02 AI Road 5"
routes["Going Across"].roads[10].direction = "with"
routes["Going Across"].roads[11] = {}
routes["Going Across"].roads[11].road = "dt_8l_centre_02 AI Road 6"
routes["Going Across"].roads[11].direction = "with"
routes["Going Across"].roads[12] = {}
routes["Going Across"].roads[12].road = "dt_shortcut_15 AI Road 0"
routes["Going Across"].roads[12].direction = "with"
routes["Going Across"].roads[13] = {}
routes["Going Across"].roads[13].road = "dt_shortcut_15 AI Road 1"
routes["Going Across"].roads[13].direction = "with"
routes["Going Across"].roads[14] = {}
routes["Going Across"].roads[14].road = "dt_10l_south_03 AI Road 3"
routes["Going Across"].roads[14].direction = "with"
routes["Going Across"].roads[15] = {}
routes["Going Across"].roads[15].road = "dt_10l_south_03 AI Road 4"
routes["Going Across"].roads[15].direction = "with"
routes["Going Across"].roads[16] = {}
routes["Going Across"].roads[16].road = "dt_10l_south_03 AI Road 5"
routes["Going Across"].roads[16].direction = "with"
routes["Going Across"].roads[17] = {}
routes["Going Across"].roads[17].road = "dt_10l_south_03 AI Road 6"
routes["Going Across"].roads[17].direction = "with"
routes["Going Across"].roads[18] = {}
routes["Going Across"].roads[18].road = "dt_10l_south_03 AI Road 7"
routes["Going Across"].roads[18].direction = "with"
routes["Going Across"].roads[19] = {}
routes["Going Across"].roads[19].road = "dt_10l_south_02b AI Road 9"
routes["Going Across"].roads[19].direction = "against"
routes["Going Across"].roads[20] = {}
routes["Going Across"].roads[20].road = "dt_10l_south_02b AI Road 8"
routes["Going Across"].roads[20].direction = "against"
routes["Going Across"].roads[21] = {}
routes["Going Across"].roads[21].road = "dt_10l_south_02b AI Road 7"
routes["Going Across"].roads[21].direction = "against"
routes["Going Across"].roads[22] = {}
routes["Going Across"].roads[22].road = "dt_10l_south_02b AI Road 6"
routes["Going Across"].roads[22].direction = "against"
routes["Going Across"].roads[23] = {}
routes["Going Across"].roads[23].road = "dt_10l_south_02b AI Road 5"
routes["Going Across"].roads[23].direction = "against"
routes["Going Across"].roads[24] = {}
routes["Going Across"].roads[24].road = "dt_10l_south_02b AI Road 4"
routes["Going Across"].roads[24].direction = "against"
routes["Going Across"].roads[25] = {}
routes["Going Across"].roads[25].road = "dt_10l_south_02b AI Road 3"
routes["Going Across"].roads[25].direction = "against"
routes["Going Across"].roads[26] = {}
routes["Going Across"].roads[26].road = "dt_10l_south_02b AI Road 2"
routes["Going Across"].roads[26].direction = "against"
routes["Going Across"].roads[27] = {}
routes["Going Across"].roads[27].road = "dt_10l_south_02b AI Road 1"
routes["Going Across"].roads[27].direction = "against"
routes["Going Across"].roads[28] = {}
routes["Going Across"].roads[28].road = "dt_10l_south_02b AI Road 0"
routes["Going Across"].roads[28].direction = "against"
routes["Going Across"].roads[29] = {}
routes["Going Across"].roads[29].road = "sutro_8l_north_01 AI Road 10"
routes["Going Across"].roads[29].direction = "against"
routes["Going Across"].roads[30] = {}
routes["Going Across"].roads[30].road = "sutro_8l_west_01 AI Road 0"
routes["Going Across"].roads[30].direction = "with"
routes["Going Across"].roads[31] = {}
routes["Going Across"].roads[31].road = "sutro_8l_west_01 AI Road 1"
routes["Going Across"].roads[31].direction = "with"
routes["Going Across"].roads[32] = {}
routes["Going Across"].roads[32].road = "sutro_8l_west_01 AI Road 2"
routes["Going Across"].roads[32].direction = "with"
routes["Going Across"].roads[33] = {}
routes["Going Across"].roads[33].road = "sutro_8l_centre_06a AI Road 0"
routes["Going Across"].roads[33].direction = "with"
routes["Going Across"].roads[34] = {}
routes["Going Across"].roads[34].road = "sutro_8l_centre_06a AI Road 1"
routes["Going Across"].roads[34].direction = "with"
routes["Going Across"].roads[35] = {}
routes["Going Across"].roads[35].road = "sutro_6l_south_01a AI Road 0"
routes["Going Across"].roads[35].direction = "with"
routes["Going Across"].roads[36] = {}
routes["Going Across"].roads[36].road = "sutro_west_03 AI Road 3"
routes["Going Across"].roads[36].direction = "with"
routes["Going Across"].roads[37] = {}
routes["Going Across"].roads[37].road = "sutro_west_03 AI Road 4"
routes["Going Across"].roads[37].direction = "with"
routes["Going Across"].roads[38] = {}
routes["Going Across"].roads[38].road = "sutro_west_03 AI Road 5"
routes["Going Across"].roads[38].direction = "with"
routes["Going Across"].roads[39] = {}
routes["Going Across"].roads[39].road = "sutro_west_03 AI Road 6"
routes["Going Across"].roads[39].direction = "with"
routes["Going Across"].roads[40] = {}
routes["Going Across"].roads[40].road = "sutro_west_03 AI Road 7"
routes["Going Across"].roads[40].direction = "with"
routes["Going Across"].roads[41] = {}
routes["Going Across"].roads[41].road = "sutro_west_03 AI Road 8"
routes["Going Across"].roads[41].direction = "with"
routes["Going Across"].roads[42] = {}
routes["Going Across"].roads[42].road = "sutro_west_03 AI Road 9"
routes["Going Across"].roads[42].direction = "with"
routes["Going Across"].roads[43] = {}
routes["Going Across"].roads[43].road = "sutro_shortcut_14 AI Road 1"
routes["Going Across"].roads[43].direction = "against"
routes["Going Across"].roads[44] = {}
routes["Going Across"].roads[44].road = "sutro_shortcut_14 AI Road 0"
routes["Going Across"].roads[44].direction = "against"
routes["Going Across"].roads[45] = {}
routes["Going Across"].roads[45].road = "sutro_south_main AI Road 6"
routes["Going Across"].roads[45].direction = "against"
routes["Going Across"].roads[46] = {}
routes["Going Across"].roads[46].road = "sutro_south_main AI Road 5"
routes["Going Across"].roads[46].direction = "against"
routes["Going Across"].roads[47] = {}
routes["Going Across"].roads[47].road = "sutro_south_main AI Road 4"
routes["Going Across"].roads[47].direction = "against"
routes["Going Across"].roads[48] = {}
routes["Going Across"].roads[48].road = "sutro_south_main AI Road 3"
routes["Going Across"].roads[48].direction = "against"
routes["Going Across"].arrows = {}

routes["Going Across Start"] = {}
routes["Going Across Start"].arrows = {}
routes["Going Across Start"].checkpoints = {}
routes["Going Across Start"].roads = {}
routes["Going Across Start"].checkpoints[1] = {}
routes["Going Across Start"].checkpoints[1].position = vec.vector(237.14799499512, 4.9130921363831, -418.59652709961, 1)
routes["Going Across Start"].checkpoints[1].heading = -1.6071519851685
routes["Going Across Start"].checkpoints[1].roadName = "dt_shortcut_07 AI Road 2"
routes["Going Across Start"].roads[1] = {}
routes["Going Across Start"].roads[1].road = "dt_shortcut_07 AI Road 2"
routes["Going Across Start"].roads[1].direction = "against"

