routes = routes or {}
routes["Scattered Checkpoints"] = {}
routes["Scattered Checkpoints"].arrows = {}
routes["Scattered Checkpoints"].checkpoints = {}
routes["Scattered Checkpoints"].roads = {}
routes["Scattered Checkpoints"].checkpoints[1] = {}
routes["Scattered Checkpoints"].checkpoints[1].position = vec.vector(-2438.886, 67.51676, 1220.639, 1)
routes["Scattered Checkpoints"].checkpoints[1].heading = -3.119903
routes["Scattered Checkpoints"].checkpoints[1].roadName = "sanfran_shortcut_09 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[2] = {}
routes["Scattered Checkpoints"].checkpoints[2].position = vec.vector(-1752.853, 50.51219, 1416.901, 1)
routes["Scattered Checkpoints"].checkpoints[2].heading = 1.724069
routes["Scattered Checkpoints"].checkpoints[2].roadName = "dt_shortcut_22 AI Road 1"
routes["Scattered Checkpoints"].checkpoints[3] = {}
routes["Scattered Checkpoints"].checkpoints[3].position = vec.vector(-2011.405, 57.25658, 1461.014, 1)
routes["Scattered Checkpoints"].checkpoints[3].heading = -1.432825
routes["Scattered Checkpoints"].checkpoints[3].roadName = "dt_shortcut_22 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[4] = {}
routes["Scattered Checkpoints"].checkpoints[4].position = vec.vector(-1296.145, 55.58415, 1483.3, 1)
routes["Scattered Checkpoints"].checkpoints[4].heading = 1.67472
routes["Scattered Checkpoints"].checkpoints[4].roadName = "dt_shortcut_23 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[5] = {}
routes["Scattered Checkpoints"].checkpoints[5].position = vec.vector(-2409.409, 62.33885, 1606.056, 1)
routes["Scattered Checkpoints"].checkpoints[5].heading = -3.06177
routes["Scattered Checkpoints"].checkpoints[5].roadName = "sanfran_shortcut_09 AI Road 2"
routes["Scattered Checkpoints"].checkpoints[6] = {}
routes["Scattered Checkpoints"].checkpoints[6].position = vec.vector(-1942.417, 64.05508, 1747.295, 1)
routes["Scattered Checkpoints"].checkpoints[6].heading = 0.1384704
routes["Scattered Checkpoints"].checkpoints[6].roadName = "r329_helper_01 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[7] = {}
routes["Scattered Checkpoints"].checkpoints[7].position = vec.vector(-2699.201, 64.91224, 1432.74, 1)
routes["Scattered Checkpoints"].checkpoints[7].heading = 2.157708
routes["Scattered Checkpoints"].checkpoints[7].roadName = "r328_helper_01 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[8] = {}
routes["Scattered Checkpoints"].checkpoints[8].position = vec.vector(-2040.469, 70.15074, 1925.129, 1)
routes["Scattered Checkpoints"].checkpoints[8].heading = 2.831717
routes["Scattered Checkpoints"].checkpoints[8].roadName = "r300_helper_01 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[9] = {}
routes["Scattered Checkpoints"].checkpoints[9].position = vec.vector(-2511.529, 63.47061, 1920.126, 1)
routes["Scattered Checkpoints"].checkpoints[9].heading = -1.600397
routes["Scattered Checkpoints"].checkpoints[9].roadName = "r299_helper_01 AI Road 0"
routes["Scattered Checkpoints"].checkpoints[10] = {}
routes["Scattered Checkpoints"].checkpoints[10].position = vec.vector(-1977.038, 55.08549, 1204.529, 1)
routes["Scattered Checkpoints"].checkpoints[10].heading = 2.506137
routes["Scattered Checkpoints"].checkpoints[10].roadName = "r358_helper_01 AI Road 0"
routes["Scattered Checkpoints"].roads[1] = {}
routes["Scattered Checkpoints"].roads[1].road = "sanfran_shortcut_09 AI Road 0"
routes["Scattered Checkpoints"].roads[1].direction = "against"
routes["Scattered Checkpoints"].roads[2] = {}
routes["Scattered Checkpoints"].roads[2].road = "dt_shortcut_22 AI Road 1"
routes["Scattered Checkpoints"].roads[2].direction = "with"
routes["Scattered Checkpoints"].roads[3] = {}
routes["Scattered Checkpoints"].roads[3].road = "dt_shortcut_22 AI Road 0"
routes["Scattered Checkpoints"].roads[3].direction = "against"
routes["Scattered Checkpoints"].roads[4] = {}
routes["Scattered Checkpoints"].roads[4].road = "dt_shortcut_23 AI Road 0"
routes["Scattered Checkpoints"].roads[4].direction = "with"
routes["Scattered Checkpoints"].roads[5] = {}
routes["Scattered Checkpoints"].roads[5].road = "sanfran_shortcut_09 AI Road 2"
routes["Scattered Checkpoints"].roads[5].direction = "against"
routes["Scattered Checkpoints"].roads[6] = {}
routes["Scattered Checkpoints"].roads[6].road = "r329_helper_01 AI Road 0"
routes["Scattered Checkpoints"].roads[6].direction = "with"
routes["Scattered Checkpoints"].roads[7] = {}
routes["Scattered Checkpoints"].roads[7].road = "r328_helper_01 AI Road 0"
routes["Scattered Checkpoints"].roads[7].direction = "with"
routes["Scattered Checkpoints"].roads[8] = {}
routes["Scattered Checkpoints"].roads[8].road = "r300_helper_01 AI Road 0"
routes["Scattered Checkpoints"].roads[8].direction = "with"
routes["Scattered Checkpoints"].roads[9] = {}
routes["Scattered Checkpoints"].roads[9].road = "r299_helper_01 AI Road 0"
routes["Scattered Checkpoints"].roads[9].direction = "with"
routes["Scattered Checkpoints"].roads[10] = {}
routes["Scattered Checkpoints"].roads[10].road = "r358_helper_01 AI Road 0"
routes["Scattered Checkpoints"].roads[10].direction = "with"
routes["Scattered Checkpoints Start"] = {}
routes["Scattered Checkpoints Start"].checkpoints = {}
routes["Scattered Checkpoints Start"].checkpoints[1] = {}
routes["Scattered Checkpoints Start"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Scattered Checkpoints Start"].checkpoints[1].heading = -2.6058
routes["Scattered Checkpoints Start"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["Scattered Checkpoints Start"].arrows = {}
routes["Scattered Checkpoints Start"].roads = {}
routes["Scattered Checkpoints Target"] = {}
routes["Scattered Checkpoints Target"].checkpoints = {}
routes["Scattered Checkpoints Target"].checkpoints[1] = {}
routes["Scattered Checkpoints Target"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Scattered Checkpoints Target"].checkpoints[1].heading = -2.6058
routes["Scattered Checkpoints Target"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["Scattered Checkpoints Target"].checkpoints[2] = {}
routes["Scattered Checkpoints Target"].checkpoints[2].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Scattered Checkpoints Target"].checkpoints[2].heading = -2.6058
routes["Scattered Checkpoints Target"].checkpoints[2].roadName = "dt_shortcut_29 AI Road 0"
routes["Scattered Checkpoints Target"].arrows = {}
routes["Scattered Checkpoints Target"].roads = {}
routes["Scattered Checkpoints Target"].roads[1] = {}
routes["Scattered Checkpoints Target"].roads[1].road = "dt_shortcut_29 AI Road 0"
routes["Scattered Checkpoints Target"].roads[1].direction = "against"
routes["Scattered Checkpoints Target"].roads[2] = {}
routes["Scattered Checkpoints Target"].roads[2].road = "dt_shortcut_29 AI Road 0"
routes["Scattered Checkpoints Target"].roads[2].direction = "with"
