routes = routes or {}
routes["Driver Madness"] = {}
routes["Driver Madness"].arrows = {}
routes["Driver Madness"].checkpoints = {}
routes["Driver Madness"].roads = {}
routes["Driver Madness"].checkpoints[1] = {}
routes["Driver Madness"].checkpoints[1].position = vec.vector(239.2289, 32.4166, 504.043, 1)
routes["Driver Madness"].checkpoints[1].heading = -2.108553
routes["Driver Madness"].checkpoints[1].roadName = "dt_8l_centre_02 AI Road 4"
routes["Driver Madness"].roads[1] = {}
routes["Driver Madness"].roads[1].road = "dt_8l_centre_02 AI Road 4"
routes["Driver Madness"].roads[1].direction = "against"
routes["Driver Madness"].checkpoints[2] = {}
routes["Driver Madness"].checkpoints[2].position = vec.vector(-513.1631, 66.26288, 294.39, 1)
routes["Driver Madness"].checkpoints[2].heading = -2.856292
routes["Driver Madness"].checkpoints[2].roadName = "dt_4l_centre_09 AI Road 2"
routes["Driver Madness"].roads[2] = {}
routes["Driver Madness"].roads[2].road = "dt_4l_centre_09 AI Road 2"
routes["Driver Madness"].roads[2].direction = "against"
routes["Driver Madness"].checkpoints[3] = {}
routes["Driver Madness"].checkpoints[3].position = vec.vector(-1089.061, 27.95558, 546.7697, 1)
routes["Driver Madness"].checkpoints[3].heading = 0.2388491
routes["Driver Madness"].checkpoints[3].roadName = "dt_6l_west_01 AI Road 1"
routes["Driver Madness"].roads[3] = {}
routes["Driver Madness"].roads[3].road = "dt_6l_west_01 AI Road 1"
routes["Driver Madness"].roads[3].direction = "with"
routes["Driver Madness"].checkpoints[4] = {}
routes["Driver Madness"].checkpoints[4].position = vec.vector(-785.7828, 32.7538, 1190.304, 1)
routes["Driver Madness"].checkpoints[4].heading = 0.3351245
routes["Driver Madness"].checkpoints[4].roadName = "chinatown_02 AI Road 2"
routes["Driver Madness"].roads[4] = {}
routes["Driver Madness"].roads[4].road = "chinatown_02 AI Road 2"
routes["Driver Madness"].roads[4].direction = "with"
routes["Driver Madness"].checkpoints[5] = {}
routes["Driver Madness"].checkpoints[5].position = vec.vector(401.7504, 20.66174, 894.5364, 1)
routes["Driver Madness"].checkpoints[5].heading = -2.824065
routes["Driver Madness"].checkpoints[5].roadName = "dt_8l_centre_02 AI Road 6"
routes["Driver Madness"].roads[5] = {}
routes["Driver Madness"].roads[5].road = "dt_8l_centre_02 AI Road 6"
routes["Driver Madness"].roads[5].direction = "against"
routes["Driver Madness"].checkpoints[6] = {}
routes["Driver Madness"].checkpoints[6].position = vec.vector(-551.2534, 22.12831, 764.3032, 1)
routes["Driver Madness"].checkpoints[6].heading = -1.647
routes["Driver Madness"].checkpoints[6].roadName = "dt_4l_centre_02 AI Road 0"
routes["Driver Madness"].roads[6] = {}
routes["Driver Madness"].roads[6].road = "dt_4l_centre_02 AI Road 0"
routes["Driver Madness"].roads[6].direction = "against"
routes["Driver Madness"].checkpoints[7] = {}
routes["Driver Madness"].checkpoints[7].position = vec.vector(-1289.468, 34.47913, 349.4714, 1)
routes["Driver Madness"].checkpoints[7].heading = -1.501557
routes["Driver Madness"].checkpoints[7].roadName = "dt_6l_west_03b AI Road 0"
routes["Driver Madness"].roads[7] = {}
routes["Driver Madness"].roads[7].road = "dt_6l_west_03b AI Road 0"
routes["Driver Madness"].roads[7].direction = "against"
routes["Driver Madness"].checkpoints[8] = {}
routes["Driver Madness"].checkpoints[8].position = vec.vector(-806.9455, 36.59116, 543.4327, 1)
routes["Driver Madness"].checkpoints[8].heading = 1.892035
routes["Driver Madness"].checkpoints[8].roadName = "dt_4l_centre_04 AI Road 2"
routes["Driver Madness"].roads[8] = {}
routes["Driver Madness"].roads[8].road = "dt_4l_centre_04 AI Road 2"
routes["Driver Madness"].roads[8].direction = "with"
routes["Driver Madness"].checkpoints[9] = {}
routes["Driver Madness"].checkpoints[9].position = vec.vector(268.1007, 16.35486, 1127.481, 1)
routes["Driver Madness"].checkpoints[9].heading = 1.777577
routes["Driver Madness"].checkpoints[9].roadName = "dt_shortcut_03b AI Road 2"
routes["Driver Madness"].roads[9] = {}
routes["Driver Madness"].roads[9].road = "dt_shortcut_03b AI Road 2"
routes["Driver Madness"].roads[9].direction = "with"
routes["Driver Madness Start"] = {}
routes["Driver Madness Start"].checkpoints = {}
routes["Driver Madness Start"].checkpoints[1] = {}
routes["Driver Madness Start"].checkpoints[1].position = vec.vector(-374.5435, 21.92724, 1153.17, 1)
routes["Driver Madness Start"].checkpoints[1].heading = -3.031042
routes["Driver Madness Start"].checkpoints[1].roadName = "chinat_shortcut_01 AI Road 0"
routes["Driver Madness Start"].arrows = {}
routes["Driver Madness Start"].roads = {}
routes["Driver Madness Target"] = {}
routes["Driver Madness Target"].checkpoints = {}
routes["Driver Madness Target"].checkpoints[1] = {}
routes["Driver Madness Target"].checkpoints[1].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Driver Madness Target"].checkpoints[1].heading = -2.6058
routes["Driver Madness Target"].checkpoints[1].roadName = "dt_shortcut_29 AI Road 0"
routes["Driver Madness Target"].checkpoints[2] = {}
routes["Driver Madness Target"].checkpoints[2].position = vec.vector(-1699.346, 74.429, 2143.131, 1)
routes["Driver Madness Target"].checkpoints[2].heading = -2.6058
routes["Driver Madness Target"].checkpoints[2].roadName = "dt_shortcut_29 AI Road 0"
routes["Driver Madness Target"].arrows = {}
routes["Driver Madness Target"].roads = {}
routes["Driver Madness Target"].roads[1] = {}
routes["Driver Madness Target"].roads[1].road = "dt_shortcut_29 AI Road 0"
routes["Driver Madness Target"].roads[1].direction = "against"
routes["Driver Madness Target"].roads[2] = {}
routes["Driver Madness Target"].roads[2].road = "dt_shortcut_29 AI Road 0"
routes["Driver Madness Target"].roads[2].direction = "with"
